### ISSUE TITLE
Glue is inserted incorrectly

### ISSUE THREAD

**Issue by strepon** [simoncozens/sile#182] opened 2015-10-15 10:53 UTC
The following code:
```
\begin[papersize=a4]{document}
\script[src=packages/lorem]
\raggedright{\glue[width=80mm]\lorem}
\end{document}
```
produces an unexpected result using the current master (and probably 0.9.3) because the glue is inserted from the right side instead of the left:
![sile_current](https://cloud.githubusercontent.com/assets/9050387/10511686/4c33fd24-733b-11e5-8836-4869baf196d3.png)

In SILE 0.9.2, everything went fine:
![sile_092](https://cloud.githubusercontent.com/assets/9050387/10511692/5c1f6200-733b-11e5-8901-e1e35eb8d1b5.png)

**Comment by simoncozens** [comment] 2015-10-15 11:37
Good catch, thank you! git bisect suggests this was caused by 269963a. Will investigate further.

**Comment by simoncozens** [comment] 2015-10-15 11:56
OK, the bug is a bit more subtle than a simple git bisect suggests.

The problem is that the "anchor" null hbox isn't added to the start of the line if the very first thing in a line is not text. If you start by pushing your own boxes onto the line (for example by using `\glue`), then the line doesn't get initialized properly. This is being fired after 269963a because our deficient whitespace handling in the TeX-like parser meant that, before that commit, there was always a bit of stray whitespace knocking around in the parse tree that got fed to `SILE.typesetter:typeset` and hence `initline` was called. 

The solution is to call `initline` in all the hmode `push...` methods. Fixed in 3477ea5.

Nice bug...

**Closed** 2015-10-15 11:56 UTC

**Comment by strepon** [comment] 2015-10-15 12:10
Thanks a lot, it works now!

**Comment by alerque** [comment] 2015-10-15 12:19
Good catch and fix but...

> there was always a bit of stray whitespace knocking around in the parse tree 

I suspect we haven't yet seen the last of this whitespace shenanigans. I'm pretty sure it's harder to typeset stuff that isn't than stuff that is!
