### ISSUE TITLE
Sile does not look up /usr/local/lib for libtexpdf.so.0

### ISSUE THREAD

**Issue by buckle2000** [simoncozens/sile#554] opened 2019-03-03 21:50 UTC
```shell
$ strace sile test.xml ^&1 | grep libtexpdf
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/tls/haswell/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/tls/haswell/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/tls/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/tls/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/haswell/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/haswell/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/tls/haswell/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/tls/haswell/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/tls/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/tls/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/haswell/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/haswell/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/tls/haswell/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/tls/haswell/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/tls/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/tls/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/haswell/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/haswell/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/tls/haswell/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/tls/haswell/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/tls/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/tls/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/haswell/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/haswell/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libtexpdf.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
write(2, "error loading module 'justenough"..., 428error loading module 'justenoughlibtexpdf' from file '/usr/local/lib/sile/justenoughlibtexpdf.so':
	libtexpdf.so.0: cannot open shared object file: No such file or directory
	/usr/local/share/sile/core/libtexpdf-output.lua:1: in main chunk
```

However, `libtexpdf.so.0` is in `/usr/local/lib`. I have to use
```sh
ln /usr/local/lib/libtexpdf.so.0.0.0 /usr/lib/libtexpdf.so.0
```
to make it work on my machine.

**Comment by alerque** [comment] 2019-03-04 05:08
What (exact) version are you running @buckle2000?

**Comment by simoncozens** [comment] 2019-03-04 08:27
Try also an `ldconfig -v` and see if it is included.

**Comment by buckle2000** [comment] 2019-03-18 01:21
> What (exact) version are you running @buckle2000?

SILE 0.9.5.1

> Try also an `ldconfig -v` and see if it is included.

`ldconfig` shows that `libtexpdf.so.0` is still installed at the wrong location.

**Comment by simoncozens** [comment] 2019-03-18 07:08
What operating system and version are you using? I'm surprised the shared library loader isn't looking in `/usr/local/lib`. Is `/usr/local/lib` in `/etc/ld.so.conf.d/libc.conf` or similar?  Have you run `sudo ldconfig`?

Does it work if you run this first? (Not suggesting this as a solution, just a diagnostic)
```
export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib
```

Have a look at these SE questions:

* https://askubuntu.com/questions/165027/why-cant-my-program-find-the-libraries-in-usr-local-lib
* https://stackoverflow.com/questions/17889799/libraries-in-usr-local-lib-not-found
* https://unix.stackexchange.com/questions/67781/use-shared-libraries-in-usr-local-lib/67783

**Comment by jamadagni** [comment] 2019-03-24 07:11
Hello. I think the problem is that the installer doesn't run `ldconfig` by itself. I just did a clean compile/install and tried to do the `sile hello.sil` but got the error:

    This is SILE 0.9.5.1
    /usr/bin/lua: error loading module 'justenoughlibtexpdf' from file '/usr/local/lib/sile/justenoughlibtexpdf.so':
            libtexpdf.so.0: cannot open shared object file: No such file or directory
    stack traceback:
            [C]: in ?
            [C]: in function 'require'
            /usr/local/share/sile/core/libtexpdf-output.lua:1: in main chunk
            [C]: in function 'require'
            /usr/local/share/sile/core/sile.lua:52: in function 'init'
            /usr/local/bin/sile:31: in main chunk
            [C]: in ?

However, once I run `sudo ldconfig` there is no problem. I think this should be fixed by adding a `ldconfig` call under the `make install` target.

**Comment by alerque** [comment] 2019-04-25 10:24
See also #275.

I don't think `make` is supposed to be responsible for running `ldconfig`, that is usually handled by post install hook scripts on various systems, and what gets run differs by distribution. If you install packages manually you're typically expected to know what else (such as library caches) need updating.

If we tried to do this in `make install` we would likely invent new problem on other systems, and in particular we would ruin packager routines that do not have root user privileges and are "installing" to a temporary output directory.

**Comment by jamadagni** [comment] 2019-04-26 16:25
OK if you think `make` shouldn't run `ldconfig` at least add to the instructions in the README:

    $ ./configure
    $ make install

as follows:

    $ sudo ldconfig

**Comment by alerque** [comment] 2019-04-28 06:17
Whether to run `ldconfig` as part of `make install` has been debated _ad nausium_ in hundreds of projects over the last decade. There are certainly pros and cons to both approaches. Here are some highlights that affect us:

* Running it does not work on OSX or Windows.
* Running it requires root, which breaks most package managers (which typically build packages using run `make install` as a non-privileged user with a custom destination and collecting the files that get created and adding them to their package). Many package managers have workarounds for this including frequently patching this out of upstream sources, providing the install environment with a wrapper instead of `ldconfig` and making the case of being called with no arguments a `noop`, or various other hacks.

A solution that appears to be frequently tried is to detect all the circumstances where this would or would not be needed. Many projects seem to have tried this and eventually reverted the code, sometimes replacing it with just an echoed warning.

Given that the only case where we need this is installs on Linux from source where people have changed the default values, I don't think we really _need_ to cater to them by coding up some fix for something the system is expected to take care of and system hackers who don't use their system's defaults should know to do. At most we can output a warning there.

**Comment by jamadagni** [comment] 2019-04-28 09:29
I don't seek to continue the ad nauseam debate. I only request clear instructions for getting things to work without unexpected errors, especially for first-time users.

> Given that the only case where we need this is installs on Linux from source where people have changed the default values

I haven't changed any default values. I have been using my own shared libraries for some of my own home-brewn apps, and every time I copy them to `/usr/local/lib` (for the first time at least) I do have to call `sudo ldconfig`.

As you can see from [the SE answer](https://askubuntu.com/a/165037/170127) to the first question @simoncozens [has referred to above](https://github.com/simoncozens/sile/issues/554#issuecomment-473793924), the simple reason is:

`/usr/local/lib` is not in the default Ubuntu path.

**Comment by alerque** [comment] 2019-04-29 05:49
@jamadagni I'm sorry if it sounded like I was accusing you of piling onto the debate, my intent was only to summarize the information I turned up in researching what should be done about this.

Regarding your situation however — if `/usr/local/lib` is not in Ubuntu's default library path, why is software getting installed there at all, and should we be taking some queue from the OS about where things _are expected_ to be installed that we're missing right now? And is `/usr/local/bin/` in the default shell path? How do you even execute `sile` if not?

**Comment by jamadagni** [comment] 2019-04-29 06:30
Hi no worries and no presumptions of accusations. 🙂

Now that I think about what you say, it does seem incongruous and maybe even factually incorrect that `/usr/local/lib` isn't in the default library path. In fact, `man ldconfig` says that  `/etc/ld.so.conf` is consulted, and that pulls in `/etc/ld.so.conf.d/libc.conf` which does mention `/usr/local/lib`.

Anyhow, I confess that I don't fully understand the mechanisms/logic of why one has to run `ldconfig` and feel it's not worth overthinking. Just advising users of the possible need to do this would be enough to close this issue. Submitted PR #596.

**Closed** 2019-04-29 08:25 UTC
Labels: packaging
