### ISSUE TITLE
Use OT rather than FT functions to query metrics from Harfbuzz

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#164] opened 2015-08-15 11:02 UTC
I don't know if this is a font version problem or a SILE problem, but `tests/vertical.sil` is being very inconsistent. Every system seems to have a different idea of how the metrics should go.

@simoncozens's system has produced one thing, yet my system is consistently producing another and the Travis test environment is producing a third set of values for the same test.

Comparing for example just the first line of the diff when tested on my system:

    -My     117.74384
    +My     117.74191

While Travis has this diff:

    -My 	117.74384
    +My 	117.73966

For reference on my system there are a whole bunch of weights for this font:

	❯ fc-list | grep 'Sans CJK JP'
	/usr/share/fonts/OTF/NotoSansCJKjp-Regular.otf: Noto Sans CJK JP,Noto Sans CJK JP Regular:style=Regular
	/usr/share/fonts/OTF/NotoSansCJKjp-Light.otf: Noto Sans CJK JP,Noto Sans CJK JP Light:style=Light,Regular
	/usr/share/fonts/OTF/NotoSansCJKjp-Thin.otf: Noto Sans CJK JP,Noto Sans CJK JP Thin:style=Thin,Regular
	/usr/share/fonts/OTF/NotoSansCJKjp-Black.otf: Noto Sans CJK JP,Noto Sans CJK JP Black:style=Black,Regular
	/usr/share/fonts/OTF/NotoSansCJKjp-Bold.otf: Noto Sans CJK JP,Noto Sans CJK JP Bold:style=Bold,Regular
	/usr/share/fonts/OTF/NotoSansCJKjp-Medium.otf: Noto Sans CJK JP,Noto Sans CJK JP Medium:style=Medium,Regular
	/usr/share/fonts/OTF/NotoSansCJKjp-DemiLight.otf: Noto Sans CJK JP,Noto Sans CJK JP DemiLight:style=DemiLight,Regular

And the default selection is actually one of the lighter weights:

    ❯ fc-match 'Noto Sans CJK JP'
    NotoSansCJKjp-DemiLight.otf: "Noto Sans CJK JP" "DemiLight"

It's possible that the issue here is font weigt selection. I played with setting `\font[weight=x]` in Sile but none of the weights matched up with the metrics currently in the master branch.

**Comment by simoncozens** [comment] 2015-08-15 11:58
> And the default selection is actually one of the lighter weights:
> 
>     ❯ fc-match 'Noto Sans CJK JP'
>     NotoSansCJKjp-DemiLight.otf: "Noto Sans CJK JP" "DemiLight"

If only things were that simple:

    $ fc-match 'Noto Sans CJK JP'
    NotoSansCJKjp-Regular.otf: "Noto Sans CJK JP" "Regular"

**Comment by alerque** [comment] 2015-08-15 11:59
Do you have the same set of available weights I do?

**Comment by simoncozens** [comment] 2015-08-15 12:00
Ah, actually I just have regular installed. However, if SILE was selecting a different weight for you, then the "Set font" line in the test output would be different. I think. You could try manually forcing the weight to 200 and seeing what you get.

**Comment by alerque** [comment] 2015-08-15 12:08
The "Set font" line in the output doesn't show a different font face no matter what weight I set (the weight value shows up, but the actual face picked isn't noted there). And 200 is the default and no setting it to 200 manually doesn't change my output. Setting it to something more or less does, but note of the values I tried neted me the same metrics as the test.

**Comment by simoncozens** [comment] 2015-08-16 19:10
OK, so I was using Noto Sans regular 1.003 whereas Travis was using Noto Sans Light 1.004. Now I am using the same version as Travis. This was discovered using our new handy font fingerprinting feature. 

I also want to add support for groking the font OpenType tables and pulling out metadata. (And, in the future, other things...)

**Comment by simoncozens** [comment] 2015-08-16 19:36
...but that hasn't helped. Now we have the same Harfbuzz version (1.0.1 on each), same font, but different metrics being returned. It's a Harfbuzz thing.

Here's Ubuntu 12:

```
$ md5sum  ~/.fonts/NotoSansCJKjp-Light.otf
f269c193b1ef0b739030d56386670c3f  /home/simon/.fonts/NotoSansCJKjp-Light.otf
$ hb-shape --direction=ttb ~/.fonts/NotoSansCJKjp-Light.otf '世界'
[gid9861=0@-500,-880+0,-1000|gid27506=1@-500,-880+0,-1000]

Build configuration:

Unicode callbacks (you want at least one):
        Glib:                   true
        ICU:                    true
        UCDN:                   false

Font callbacks (the more the better):
        FreeType:               true

Tools used for command-line utilities:
        Cairo:                  false
        Fontconfig:             true

Additional shapers (the more the better):
        Graphite2:              false
```

Here's OS X:

```
$ md5sum /Users/simon/Library/Fonts/NotoSansCJKjp-Light.otf
f269c193b1ef0b739030d56386670c3f  /Users/simon/Library/Fonts/NotoSansCJKjp-Light.otf
$ hb-shape --direction=ttb /Users/simon/Library/Fonts/NotoSansCJKjp-Light.otf '<00e4><00b8><0096><00e7><0095><008c>'
[gid9861=0@-500,-894+0,-1000|gid27506=1@-500,-894+0,-1000]

Build configuration:

Unicode callbacks (you want at least one):
    Glib:           true
    ICU:            true
    UCDN:           false

Font callbacks (the more the better):
    FreeType:       true

Tools used for command-line utilities:
    Cairo:          true
    Fontconfig:     true

Additional shapers (the more the better):
    Graphite2:      false

Platform shapers (not normally needed):
    CoreText:       false
    Uniscribe:      false
```

@behdad, help?

**Comment by behdad** [comment] 2015-08-18 23:36
It's caused by some FreeType weirdness on OS X that I never spent the time to track down.  Switching away from hb-ft to hb-ot for font funcs implementation (eg, --font-funcs=ot passed to hb-shape) should address this.

**Comment by simoncozens** [comment] 2015-08-19 18:46
That works for hb-shape; excellent. But SILE can't move to the OT funcs until `hb_ot_get_glyph_extents` is implemented. So I guess we make the tests work on Travis. (and fail for me.)

**Comment by behdad** [comment] 2015-08-20 09:48
> SILE can't move to the OT funcs until hb_ot_get_glyph_extents is implemented.

That's on my todo for today.

**Comment by alerque** [comment] 2015-08-21 07:10
@simoncozens I added ad update to the expected output of this test to another test output related PR to bring the Travis test run that much closer to passing ever though this issue is outstanding.

**Comment by simoncozens** [comment] 2015-08-21 07:14
@alerque: I'm not sure this is needed now; I spent some time blitzing test results last night and now we're down to [two failing builds](https://travis-ci.org/simoncozens/sile/builds/76533770) - neither are related to font metrics: one is for the non-ICU tokenizer, and one is some Lua 5.1 UTF8 weirdness.

**Comment by behdad** [comment] 2015-08-23 13:45
> SILE can't move to the OT funcs until hb_ot_get_glyph_extents is implemented.
> 
> That's on my todo for today.

In HarfBuzz master now.  Please test.  It's my intention to implement vertical positioning using glyf table as well as VORG table, and then make a release.  At that point ot-font will have better vertical support than FreeType (which doesn't implement VORG at all).

**Comment by simoncozens** [comment] 2015-08-23 17:24
Thank you! This looks good. Most things work - it gives different metrics to FreeType so obviously most of the regression tests fail. Japanese, Javanese, Tibetan and Arabic work nicely.

Something goes horribly wrong when I try to typeset the documentation file, let's see... lots of tofu when I use Helvetica Neue, but probably because it's a dfont, d'oh. Ah, now, something goes mad with Gentium Book Basic. x_advance and glyph width are fine but metrics are out of whack:

```lua
> SILE.shaper:shapeToken("SILE", SILE.font.loadDefaults({ font = "Gentium Book Basic" }))
{
  {
    codepoint = 54,
    depth = 3.57421875,
    glyphWidth = 91.2451171875,
    height = 8.7939453125,
    index = 0,
    name = "",
    width = 4.8828125,
  },
  {
    codepoint = 44,
    depth = -3.1982421875,
    glyphWidth = 35.1123046875,
    height = 103.1298828125,
    index = 1,
    name = "",
    width = 3.076171875,
  },
  {
    codepoint = 47,
    depth = -11.7041015625,
    glyphWidth = 97.5,
    height = 22.5,
    index = 2,
    name = "",
    width = 4.873046875,
  },
  {
    codepoint = 40,
    depth = -17.5,
    glyphWidth = 119.4482421875,
    height = 81.2744140625,
    index = 3,
    name = "",
    width = 5.05859375,
  },
}
```

Compare:

```lua
> SILE.shaper:shapeToken("SILE", SILE.font.loadDefaults({ font = "Gentium" }))
{
  {
    codepoint = 51,
    depth = 0.146484375,
    glyphWidth = 3.75,
    height = 6.298828125,
    index = 0,
    name = "",
    width = 4.7607421875,
  },
  {
    codepoint = 41,
    depth = 0,
    glyphWidth = 2.197265625,
    height = 6.15234375,
    index = 1,
    name = "",
    width = 2.978515625,
  },
  {
    codepoint = 44,
    depth = 0,
    glyphWidth = 4.365234375,
    height = 6.15234375,
    index = 2,
    name = "",
    width = 4.7607421875,
  },
  {
    codepoint = 37,
    depth = 0,
    glyphWidth = 4.4140625,
    height = 6.15234375,
    index = 3,
    name = "",
    width = 4.9609375,
  },
}
```

Otherwise, nice job. Now we have to decide whether or not to make harfbuzz >1.0.3 a dependency. ;-)

**Comment by behdad** [comment] 2015-08-23 18:51
> Something goes horribly wrong when I try to typeset the documentation file, let's see...
> lots of tofu when I use Helvetica Neue, but probably because it's a dfont, d'oh.

Yeah.  It's easy to implement.  Lets see.  Filed https://github.com/behdad/harfbuzz/issues/128 cc @brawer.

> Ah, now, something goes mad with Gentium Book Basic. x_advance is fine but metrics are out of whack:

That's weird.  I don't have a simple tool to write out the extents.  Let me implement something like that and test..

**Comment by simoncozens** [comment] 2015-08-23 19:16
I'll do it!

**Comment by simoncozens** [comment] 2015-08-23 19:23
Boom:

```
$ ./util/hb-shape --font-funcs=ot --show-extents ~/Library/Fonts/GenBkBasR.ttf 'SILE'
[gid54=0+1000<2564,1801,18687,-2533>|gid44=1+630<15640,21121,7191,-20466>|gid47=2+998<-17920,4608,19968,-2211>|gid40=3+1036<1905,16645,24463,-13061>]
$ ./util/hb-shape --font-funcs=ft --show-extents ~/Library/Fonts/GenBkBasR.ttf 'SILE'
[S=0+1000<112,1290,801,-1320>|I=1+630<68,1260,475,-1260>|L=2+998<48,1260,921,-1260>|E=3+1036<48,1260,931,-1260>]
```

Boom.

**Comment by behdad** [comment] 2015-08-23 19:34
Awesome.  Thanks.  Pull-request please? :)

**Comment by behdad** [comment] 2015-08-24 12:45
Fixed now.

**Comment by simoncozens** [comment] 2015-08-24 13:28
That works really nicely; thanks @behdad!

Now - what do we do about SILE? The original bug isn't really a problem any more because Travis is now passing most tests (and those that are failing are to do with ICU emulation). So we don't *need* the OT branch. Do we want it?

Pros:

* 28% speedup! (Freetype SILE compiles 117 page Matigsalug Genesis in 81 seconds; Harfbuzz SILE does it in 113. Similar numbers in other tests.)
* Gives consistent metrics across platforms.
* Allows us to drop the Freetype dependency. (Is that useful? We're using fontconfig and Harfbuzz and I bet if you have those packages installed you're using something that depends on Freetype anyway.)

Cons:

* Bleeding edge feature so not likely to be in any distributions for ages.
* No dfont support yet (but that's coming soon.)

I think it's something that we do want eventually but depending on bleeding-edge scares me. Perhaps the right approach is to test if the OT features work and use them if available, but that makes the code complicated... Any other opinions?

**Comment by behdad** [comment] 2015-08-24 13:33
> That works really nicely; thanks @behdad!

Cool.


> Now - what do we do about SILE? The original bug isn't really a problem any more because Travis is now passing most tests (and those that are failing are to do with ICU emulation). So we don't need the OT branch. Do we want it?
> 
> Pros:
> 
>     28% speedup! (Freetype SILE compiles 117 page Matigsalug Genesis in 81 seconds; Harfbuzz SILE does it in 113. Similar numbers in other tests.)

I'm confused by the numbers...

Note that I have not yet optimized hb-ot-font...  But this is a great test case for our performance.

>     Gives consistent metrics across platforms.
>     Allows us to drop the Freetype dependency. (Is that useful? We're using fontconfig and Harfbuzz and I bet if you have those packages installed you're using something that depends on Freetype anyway.)

In the end I think you should drop FreeType.  It's a rasterizer and has no place in a layout system.

> Cons:
> 
>     Bleeding edge feature so not likely to be in any distributions for ages.
>     No dfont support yet (but that's coming soon.)
> 
> I think it's something that we do want eventually but depending on bleeding-edge scares me. Perhaps the right approach is to test if the OT features work and use them if available, but that makes the code complicated... Any other opinions?

Yeah, wait until hb-ot-font is complete.  Needs VORG and glyph-name implementations.  Other than that, it's also missing CFF support.  Normally you don't need glyph extents with CFF as CFF fonts should have GPOS...  However, if you rely on glyph extents in Sile (why do you?) then that's a problem.

So yeah, for now, lets work towards that goal, but don't rush switching just yet.

**Comment by behdad** [comment] 2015-08-24 13:34
And yes, you can always decided which one to use at runtime.

**Comment by simoncozens** [comment] 2015-08-24 14:00
Ah, I was just trying to debug why Japanese wasn't working. :-)

SILE uses x_advances for width (and y_advance for height in vertical layouts), but it also uses glyph height and depth information for [computing the leading between successive baselines](https://books.google.co.uk/books?id=72wKBwAAQBAJ&pg=PA93&lpg=PA93&dq=tex+lineskip&source=bl&ots=_m1pi5Kg3I&sig=EXAcAanKuagxKFSozs8qL2sRp8g&hl=en&sa=X&redir_esc=y#v=onepage&q&f=false).

**Comment by simoncozens** [comment] 2015-08-24 14:40
>> 28% speedup! (Freetype SILE compiles 117 page Matigsalug Genesis in 81 seconds; Harfbuzz SILE does it in 113. Similar numbers in other tests.)
> I'm confused by the numbers...

Yeah, other way around. :-) Using FreeType was 113s, OT-features did it in 81s.

**Comment by behdad** [comment] 2015-08-25 11:51
Yeah, we'd need to implement CFF glyph extents then (which we should cache... how's the performance with FT with CFF fonts BTW?  Should be awful...)

**Comment by simoncozens** [comment] 2015-10-11 13:01
We're doing this now. It seems to work (even vertically-typeset Japanese) without the CFF glyph extents.

**Closed by simoncozens** 2015-10-11 13:01 UTC
Labels: enhancement, low priority
