### ISSUE TITLE
Glues being discarded when useful and kept when not

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#303] opened 2016-04-01 14:44 UTC
Something in the last month or so has changed the behavior of glues in various places and they are being discarded is some situations where I need them and dropped in others.

For example they are being discarded here (unless I put an hbox on the line first!):

``` XML
<sile papersize="a7">
  <script>
	SILE.registerCommand("poetry", function(options, content)
		SILE.settings.temporarily(function()
			SILE.typesetter:leaveHmode()
			SILE.settings.set("document.lskip", SILE.nodefactory.newGlue("1em"))
			SILE.settings.set("document.rskip", SILE.nodefactory.hfillGlue)
			SILE.settings.set("current.parindent", SILE.nodefactory.zeroGlue)
			SILE.settings.set("document.parindent", SILE.nodefactory.zeroGlue)
			SILE.process(content)
			SILE.call("par")
		end)
	end)
  </script>
  <poetry>Line 1<break /><qquad />Line 2<break />Line 3<break /><hbox /><qquad />Line 4</poetry>
</sile>
```
![selection_191](https://cloud.githubusercontent.com/assets/173595/14210304/1ca8a8cc-f831-11e5-8104-e8c07beb5747.png)

In a counter-example, I have a section command defined like this:

``` Lua
SILE.registerCommand("section", function (options, content)
  SILE.typesetter:leaveHmode()
  SILE.call("goodbreak")
  SILE.call("skip", {height="12pt plus 6pt minus 4pt"})
  SILE.call("noindent")
  SILE.settings.temporarily(function()
    SILE.call("book:sectionfont", {}, function()
      SILE.call("uppercase", {}, content)
    end)
  end)
  SILE.call("novbreak")
end, "Begin a new section")
```
![selection_192](https://cloud.githubusercontent.com/assets/173595/14210343/45944cfa-f831-11e5-8f18-8fc1487d7edf.png)

This used to work with space between paragraph→section unless the section was at the top of the page and it would be discarded. Now the space is still there even as the first thing on a page.

**Comment by simoncozens** [comment] 2016-05-27 11:41
78d8bddc2bb24a7ef803582782025e0a1d796ce2 is the first bad commit
    commit 78d8bddc2bb24a7ef803582782025e0a1d796ce2
    Author: Simon Cozens <simon@simon-cozens.org>
    Date:   Tue Mar 15 23:11:19 2016 +1100

        Fix #284 by shifting out the discardables before adding lskip

**Comment by alerque** [comment] 2016-06-02 08:25
The second half of this (not collapsing space that usually would be) only happens on pages after pages that have footnotes. See part b of the tests I added.

**Comment by simoncozens** [comment] 2016-06-10 00:29
The second case has been fixed elsewhere.

The first case is due to the fact that `\break` doesn't really do what it sounds like. It says "you may break here" but doesn't actually initialize a new line by sticking an empty hbox at the start of the line. That means any glue after that line break can legitimately be swallowed up. This is counter-intuitive but I think it's correct. The way to work around that is to redefine `\break` to include a `\hbox`. Unfortunately that trips bug #254. Urgh.

**Comment by simoncozens** [comment] 2016-06-22 07:16
Yeah, I think I'm going to close this as (unfortunately) not a bug. The workaround is that if you want glue which is explicitly not going to be swallowed up, use a kern instead.

**Closed by simoncozens** 2016-06-22 07:16 UTC

**Comment by alerque** [comment] 2016-07-15 10:13
Kerns are non-discardable Glues. Check.

Perhaps we should document this as I don't think I'm going to be the only one struggling with when things get discarded.
