### ISSUE TITLE
Harfbuzz with Graphite is messing up Arabic

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#124] opened 2015-07-01 11:41 UTC
I'm still trying to track down issues with the regression tests across platforms. For some reason Arabic doesn't want to behave itself. Specifically the `tests/arabic.sil` file (as current in my #122 PR) doesn't compile the same way on any of OSX, my Linux system or Travis's environment. All three systems now have exactly the same font versions, so that's not the issue. Perhaps you can point me in the direction of what _could be_ the issue.

As you can see here, the leading migrates with the OSX version being larger (in black here):

![arabic-offset](https://cloud.githubusercontent.com/assets/173595/8453600/d23609c0-1ffe-11e5-9ddd-631d6d51c234.png)

Additionally, there are individual character differences in various places. Some of them are subtle, others less so (OSX version on the right):

![diffpdf_028](https://cloud.githubusercontent.com/assets/173595/8453619/fd5c7774-1ffe-11e5-9131-a20bf7169725.png)

Is this an issue with font-config? Harfbuzz? Where could these differences be introduced that would vary three ways between systems? Note I'm not seeing this in any of the English language tests.

**Comment by simoncozens** [comment] 2015-07-01 11:52
I would guess Harfbuzz or freetype?

**Comment by alerque** [comment] 2015-07-01 12:27
That looks like a promising lead but:

* OSX + Harfbuzz 0.9.41 + Freetype 2.6.1 produce the same output as Ubuntu + Harfbuzz 0.9.26 + Freetype 2.4.8 while Arch + Harfbuzz 0.9.40 + Freetype 2.5.5 is, in this case, the different one. That doesn't sound like the culprit since it's bracketed.
* In a similar issue (this time with images rather than with Arabic, the latter two are the same while the first is the odd one out.

What else could it be? Could Lua 5.3 vs. 5.2 be throwing this off somehow?

**Comment by khaledhosny** [comment] 2015-07-01 13:18
The image on the left is certainly wrong. It does not look like a HarfBuzz issue to me (unless Scheherazade is decomposing the Alef and positioning the Hamza as a combining mark).

**Comment by simoncozens** [comment] 2015-07-01 13:27
@alerque, what do you mean that images are wrong? If images are not being sized properly, then we can ignore fonts/Harfbuzz/Freetype and just concentrate on Lua.

**Comment by alerque** [comment] 2015-07-01 13:50
@simoncozens Okay my bad. I didn't examine that one closely enough and now that I have it's clearly a different sort of problem. That's a float vs. int output problem throwing off the debugger. The generated PDF is identical.

	git diff -U0
	diff --git a/tests/image.expected b/tests/image.expected
	index 0161319..3da9998 100644
	--- a/tests/image.expected
	+++ b/tests/image.expected
	@@ -11 +11 @@ T 84 87 79    (two)
	-Draw image documentation/fig1.png  77.985571410771 29.76377985 50.0    69.242902208202
	+Draw image documentation/fig1.png  77.985571410771 29.76377985 50  69.242902208202
	@@ -19 +19 @@ T 84 87 79    (two)
	-Draw image documentation/fig1.png  77.988630333249 117.1531664332  36.104783599089 50.0
	+Draw image documentation/fig1.png  77.988630333249 117.1531664332  36.104783599089 50

@khaledhosny Thanks for the insight. My Turkish doesn't get me very far into Arabic! BTW, as of a few minutes ago your fork of Libertine is available as a [Homebrew Cask](https://github.com/caskroom/homebrew-fonts/) (`brew tap caskroom/fonts; brew cask install font-libertine`) and an [Archlinux package](https://aur4.archlinux.org/packages/otf-libertine-git/).

**Comment by alerque** [comment] 2015-07-01 15:18
Alright I've confirmed that:

* This is font specific. Half a dozen other Arabic fonts work fine and are consistent in both places.
* The same problem surfaces with this font in other files with Arabic text.
* It is _not_ a difference in font versions. I've stripped all systems down of all copies of the font (confirmed sile couldn't find it at all) then added in the raw TTF file from the working systems to the one that was failing. Same TTF, different output.
* It's _not_ Lua version specific. Travis is finally good for something today. If it was 5.3 related I would have expected 2 of [these builds](https://travis-ci.org/alerque/sile/builds/69150903) to succeed.

Was going to try same font + content in LaTeX / other apps but ran out of time, will edit this when I do...

**Comment by alerque** [comment] 2015-07-02 07:56
So this does seem to be SILE specific. The same content rendered in the same font on the same system in Firefox, Chromium, LibreOffice and XeLaTeX all work fine. All of those have slightly different font rendering pipelines, but none of them have a problem with positioning the Arabic diacritic marks.

Here is a minimal working SILE example:

	\begin[papersize=a5]{document}
	\script[src=packages/bidi]
	\font[size=40pt,language=ar,script=Arab]
	\thisframeRTL
	\font[family=Noto Naskh Arabic]{ألمّ} — \font[family=Scheherazade]{ألمّ}
	\end{document}

![bug-124 pdf_032](https://cloud.githubusercontent.com/assets/173595/8472325/eed0f428-20a8-11e5-95f2-a1b01663617d.png)

And here is a LaTeX equivalent:

	\documentclass[a5paper,40pt]{scrartcl}
	\usepackage{polyglossia}
	\setdefaultlanguage{english}
	\setotherlanguage{arabic}
	\newfontfamily\scheherazade[Script=Arabic]{Scheherazade}
	\newfontfamily\notonaskh[Script=Arabic]{Noto Naskh Arabic}
	\begin{document}
	\RTL
	\textarabic{\notonaskh ألمّ} --- \textarabic{\scheherazade ألمّ}
	\end{document}

![bug-124 sil pdf_031](https://cloud.githubusercontent.com/assets/173595/8472327/f4dea306-20a8-11e5-8f73-11b550634a39.png)

**Comment by alerque** [comment] 2015-07-02 08:44
As I surmised would be the case based on [newer and older versions working on other systems](https://github.com/simoncozens/sile/issues/124#issuecomment-117640281), updating my system to Freetype 2.6 and Harfbuzz 0.9.41 and recompiling SILE made no difference.

**Comment by simoncozens** [comment] 2015-07-06 22:29
@khaledhosny: That is exactly what is happening. Noto Sans is returning a U+0623 Alef+Hamza above for the rightmost glyph; Scheherezade is returning this:

```lua
  {
    codepoint = 272,
    depth = 0.029296875,
    height = 4.8291015625,
    name = "uni0627",
    width = 1.4501953125,
  },
  {
    codepoint = 1052,
    depth = -4.931640625,
    height = 6.4794921875,
    name = "uni0654",
    width = 0,
    x_offset = -0.046875,
    y_offset = 0.375,
  },
}
```

**Comment by alerque** [comment] 2015-07-07 04:37
That's interesting, but what could be cause some systems to typeset Scheherezade correctly while others trip up over the two points?

**Comment by simoncozens** [comment] 2015-07-07 05:10
Graphite installed versus not installed?

**Comment by alerque** [comment] 2015-07-07 05:37
Maybe. In that event ① it is the _with_ variant that is failing and ② I'm not sure how I can even test it without. My system's harfbuzz package depends on it, as do a bunch of other things.

**Comment by simoncozens** [comment] 2015-07-07 05:47
Bingo - it's a graphite problem. (Paging @khaledhosny)

And it's easy to test with Homebrew now. :-)

```
brew uninstall harfbuzz; brew install harfbuzz; ./sile examples/bug-124.sil
```

produces this:

![bug-124-without-graphite](https://cloud.githubusercontent.com/assets/106728/8539464/1cf38ee4-24b7-11e5-96ec-9fbbc172b11a.png)

```
brew uninstall harfbuzz; brew install harfbuzz --with-graphite2; ./sile examples/bug-124.sil
```

produces this:

![bug-124-with-graphite](https://cloud.githubusercontent.com/assets/106728/8539453/ecd6dc3e-24b6-11e5-9c71-4563c89c3453.png)

**Comment by khaledhosny** [comment] 2015-07-07 07:58
I can reproduce it with `hb-view`, with `graphite2:

    hb-view /usr/share/fonts/TTF/scheherazade.ttf --shapers=graphite2 ألمّ
![scheherazade-gr2](https://cloud.githubusercontent.com/assets/93914/8541355/caa55588-248d-11e5-9708-ce45268effde.png)

    hb-view /usr/share/fonts/TTF/scheherazade.ttf --shapers=ot ألمّ
![scheherazade-ot](https://cloud.githubusercontent.com/assets/93914/8541365/d906312e-248d-11e5-9345-4328895fd3a7.png)

So it looks like a Graphite bug or (more likely) a bug in Graphite integration in HarfBuzz. I wonder if the patch in http://lists.freedesktop.org/archives/harfbuzz/2015-June/004902.html handles this. CC @mhosken.

**Comment by mhosken** [comment] 2015-07-07 12:12
Dear Khaled,

> I can reproduce it with `hb-view`, with `graphite2:
> 
>     hb-view /usr/share/fonts/TTF/scheherazade.ttf --shapers=graphite2 ألمّ
> ![scheherazade-gr2](https://cloud.githubusercontent.com/assets/93914/8541355/caa55588-248d-11e5-9708-ce45268effde.png)
> 
>     hb-view /usr/share/fonts/TTF/scheherazade.ttf --shapers=ot ألمّ
> ![scheherazade-ot](https://cloud.githubusercontent.com/assets/93914/8541365/d906312e-248d-11e5-9345-4328895fd3a7.png)
> 
> So it looks like a Graphite bug or (more likely) a bug in Graphite integration in HarfBuzz. I wonder if the patch in http://lists.freedesktop.org/archives/harfbuzz/2015-June/004902.html handles this. CC @mhosken.

Yes. This is fixed by that patch. Just waiting for it to be applied.

Yours,
Martin

**Comment by simoncozens** [comment] 2015-07-07 13:54
Well, this isn't a SILE bug, so I'm closing it. Will be fixed next time @behdad releases Harfbuzz.

**Closed by simoncozens** 2015-07-07 13:54 UTC

**Comment by behdad** [comment] 2015-07-26 20:35
New HarfBuzz should have the fix.

**Comment by alerque** [comment] 2015-07-27 05:56
Spiffy. Thanks for the release and the heads up @behdad!
