### ISSUE TITLE
weird issues on OS X

### ISSUE THREAD

**Issue by jyrgenn** [simoncozens/sile#68] opened 2015-04-13 08:14 UTC
When I installed SILE 0.9.1 on OS X (10.10.3), I encountered a few weird issues. While the configure and build goes fine once I installed the necessary prerequisites, I see this when I try the examples:

    $ sile examples/test
    This is SILE 0.9.1
    <examples/test.sil><examples/macros.sil>[1] [2] [3] [4] [5] [6] [7] [8] [9] [10] [11] [12] [13] [14] [15] [16] [17] [18] [19] [20] [21] [22] [23] [24] [25] 
    libtexpdf:fatal: Invalid font: -1 (10)

    $ sile examples/showoff
    This is SILE 0.9.1
    <examples/showoff.sil>[1] No patterns for language ja
    [2] [3] [4] 

The apparent error in the latter case may be a minor problem, as I haven't just done anything with Japanese before. The output file shows the Japanese letters fine, though, but the Arabic ones are replaced by boxes.

    $ sile examples/osis/kjv
    This is SILE 0.9.1
    <examples/osis/kjv.sil>/usr/local/bin/lua: core/sile.lua:147: bad argument #1 to 'open' (string expected, got nil)
    stack traceback:
	[C]: in function 'open'
	core/sile.lua:147: in function 'readFile'
	core/baseclass.lua:54: in function '?'
	core/inputs-common.lua:26: in function 'process'
	core/inputs-texlike.lua:56: in function 'process'
	core/sile.lua:159: in function 'readFile'
	/opt/w21/bin/sile:23: in main chunk
	[C]: in ?

Here I thought this might just not find an include file in the sub-sub-directory. But when I change to that, an even stranger error appears:

    : wrixum:1:.../sw/sile-0.9.1; cd examples/osis
    : wrixum:0:.../examples/osis; sile kjv
    This is SILE 0.9.1
    <kjv.sil><osis.sil>
    ! Couldn't parse font size 9 in osis.sil

I *have* tried to replace the 9 with a 10, only then it complains about the 10.

Now all those problems may be there because I have overlooked something. I am not really sure the Lua installation is totally okay, for instance, as I have never done anything with Lua (and have no real knowledge of the language).

A typescript -- slightly edited to spare you my command line edits -- of the above, including configure and build, can be seen here:

https://gist.github.com/jyrgenn/a03685ee8f3ce1c1f8f6#file-typescript_sile-bug

There are a few compile warnings indicating pointer type mismatches, but I guess they are harmless.

Versions of the involved software:
  * OS X 10.10.3
  * SILE 0.9.1 as from https://github.com/simoncozens/sile/releases/download/v0.9.1/sile-0.9.1.tar.gz
  * Lua 5.2.3, LuaRocks 2.2.0 (via Homebrew)

Installed rocks:

lgi
   0.9.0-1 (installed) - /usr/local/lib/luarocks/rocks
lpeg
   0.12.2-1 (installed) - /usr/local/lib/luarocks/rocks
luaexpat
   1.3.0-1 (installed) - /usr/local/lib/luarocks/rocks

I have upgraded all Homebrew-installed packages before the build, so they should be as current as the Homebrew collection is. They are:

atk gdk-pixbuf intltool meld pygtksourceview bdw-gc geoip jasper mercurial python berkeley-db gettext jpeg nettle quvi berkeley-db4 glib libffi nmap rarian c-ares gmp libgcrypt nvi readline cairo gnu-sed libgpg-error openssl sbcl clisp gnuplot libpng p7zip sdl cscope gnutls libquvi pango sqlite d-bus gobject-introspection libsigsegv pixman w3m fish graphviz libtasn1 pkg-config wget fontconfig gtk+ libtiff pwgen wireshark freetype gtksourceview lua py2cairo xz gd harfbuzz luarocks pygobject gdbm icu4c lynx pygtk

Configure line:
    ./configure --prefix=/opt/w21

I use the alternative prefix because Homebrew occupies /usr/local and can get confused when there is other stuff in `/usr/local/`. `/opt/w21/bin` is in `PATH`.

As mentioned, my knowledge of Lua is next to non-existing, although I skimmed the canonical Lua books once, so I don't know how to proceed from here. I will happily try anything to narrow down the problem if you give me some guidance, or anything else that might be helpful.

**Comment by jyrgenn** [comment] 2015-04-13 08:17
Screen shot of the botched showoff output
![screen shot 2015-04-13 at 10 16 41](https://cloud.githubusercontent.com/assets/11918910/7112057/3b5495ce-e1c6-11e4-9045-37cbcc1d98ae.png)

**Comment by jyrgenn** [comment] 2015-04-13 08:22
I haven't found the `tests/attack.pl` in the 0.9.1 tar file; I'll try to continue with the current repo version soonish, but have to run now.

**Comment by simoncozens** [comment] 2015-04-13 11:57
Hi Jurgen, I think most of these are actually not problems. There've been a few fixes to missing font errors in the repo---you'll now get "Could not find requested font XYZ" instead of "Invalid font (-1)".

The "no patterns for language ja" is not an error, because you can't hyphenate Japanese. This warning has been suppressed in the repo.

Arabic won't work if you don't have the requested Arabic font (in the examples, Scheherazade) installed.

The KJV example has a bug where the examples were not updated after change in the way font sizes are specified. (previously, points were assumed as the unit of measurement; now a unit is explicitly required) That's also fixed in the repo.

Actually lots of things are fixed in the repo, and we really should prepare for a release very soon...

**Closed by simoncozens** 2015-04-13 11:57 UTC

**Comment by jyrgenn** [comment] 2015-04-13 13:10
Hi Simon, thanks for the clarifications – I know 0.9.1 is a 0.x release, so the full perfection of a 1.0 release must not be expected :–), but I was still afraid I had a bad build. Thanks again!

**Comment by alerque** [comment] 2015-07-02 09:02
It's not easier than ever to to play with the repo version on OSX if you are still interested

    brew install sile --HEAD

That will get you the latest version out of git with all the dependencies. That's the easiest way to get started and have all the parts (note, use Homebrew command `reinstall` to upgrade head packages). But that doesn't get you the actual repository or the ability to play with the stuff in it such as regression tests. This will:

    git clone git@github.com:simoncozens/sile.git
    cd sile
    ./bootstrap.sh && ./configure && make

Since your system already has the necessary dependencies having installed from Homebrew above, this should be a shoe it. Now your system default `sile` executable is the one installed from Homebrew but you can also run the one you compiled in you repo using `./sile`. You can hack on the lua code in your repo and run it without needed to do the above compile step. With that in mind, the tests should work:

    perl tests/attack.pl --regression

…since the test script uses `./sile` internally to test the local repo instead of any system installed version of SILE.

Note: as soon as #122 gets merged the test system should run a lot smoother and `./tests/attack.pl --regression` will only run the regression tests and will need to be run without the flag as just `./tests/attack.pl` to check compiling of the examples.
