### ISSUE TITLE
Package contribution / publishing

### ISSUE THREAD

**Issue by oleastre** [simoncozens/sile#60] opened 2015-03-13 23:48 UTC
As I started playing with SILE to create songbooks (trying to replace my current LaTeX version), I started writing some packages to help me (with a growing TODO list) and I would like to share that work and get feedback.

So, what is your preferred way to contribute those packages ?
Make pull requests ? 
Create a "contrib" folder in SILE ?
Publish them in my own repo ?
Discuss each one to see if it should be published as "contrib" or integrated ?

For example I did a "chord mode" package that typeset chord names above the text:
Input:
```tex
\begin[papersize=a4,class=songbook]{document}

\script[src=packages/chordmode]

\begin{chordmode}

  I've be<G>en a wild rover for many's a <C>year

  And I <G>spent all me <D7>money on whiskey and <G>beer

  But now I'm returning with gold in great <C>store

  And I <G>never will <D7>play The Wild Rover no <G>more.

\end{chordmode}

\end{document}

```
Result (the page background is defined in a specific class):
![chordmode-example](https://cloud.githubusercontent.com/assets/838332/6648864/940dcde2-c9df-11e4-8050-feb805333183.png)

**Comment by simoncozens** [comment] 2015-03-20 04:21
This is very cool! It also raises a few questions I need to think about... I will have to think about a good way for packages to be distributed and installed, and also the presence of external packages definitely increases the need for backward-compability, freezing interfaces and so on. So I will have to check through to see that I am happy with how everything works at present.

I have also been thinking about a generic mechanism to allow filters to the TeX-like input, which I guess is how you implemented `chordmode` above. That would allow us to do things like e.g. typesetting Markdown.

For now, could you send me pull requests and I'll take the pieces that would be appropriate for core?

**Comment by oleastre** [comment] 2015-03-20 09:39
From my point of view, I would not worry about backward compatibility before you have all the core features implemented (the current roadmap ?). 
The best way is maybe to document breaking changes, so it's easy for package creators to update.

Before I do a PR, I have to do some cleanup on the chord mode and extract the content table manipulation hack in it's own package.

**Comment by alerque** [comment] 2016-08-12 11:21
This is basically a duplicate of #324 which has at least a temporary resolution.

**Closed by alerque** 2016-08-12 11:21 UTC
