### ISSUE TITLE
Allow including TeX-flavor fragments instead of only whole documents

### ISSUE THREAD

**Issue by kappa2222** [simoncozens/sile#505] opened 2017-12-25 22:00 UTC
Hello. I have two `.sil` files

    % include/test.sil
    \define[command=xxx]{expanded thing}

and

    \begin{document}
    % aaa.sil
    \include[src=include/test.sil]
    % the following is line 10
    \xxx       
    \end{document}                                                

When I compile this example I get:

    This is SILE 0.9.4
    <../somefolder/aaa.sil>
    <../somefolder//include/test.sil>

    ! Unknown command xxx at include/test.sil l.10, col.1

I invoke sile like:

     # from the folder where I built sile
    ./sile -o ../somefolder/cv.pdf ../somefolder/aaa.sil

At first I thought Sile was not reading the file to include, but it's not like that because if I pass \\include a wrong path I get a meaningful file-not-found error. Notice also the filename in the error message (which refers to the included) and the line (which refers to the includee).

**Comment by simoncozens** [comment] 2017-12-26 01:44
Urgh, this is really bad. Sorry.

Note to self: `SILE.inputs.TeXlike.process` does not seem to do anything when a documentclass is already defined. I blame @alerque for 97a4e3e8, but I'm not sure if that's fair or not.

**Comment by alerque** [comment] 2017-12-26 06:34
Is the `% include/test.sil` bit in your .sil file or was that just for the sake of your Github post? If the former this might be an iteration of #502.

I'll try to have a look today and see if I can figure out what's up.

**Comment by kappa2222** [comment] 2017-12-26 06:37
> Is the % include/test.sil bit in your .sil file or was that just for the sake of your Github post

For the sake of the github post.

**Comment by alerque** [comment] 2017-12-26 08:21
Wow yes this is as sticky little cart/horse problem. Our file type detection wants to have its cake and eat it too, but I'm struggling to visualize how we can have both sets of nice things. I suspect the answer is going to be to stop trying to guess file types and just expect one of the other. We can't simultaneously sniff file types, allow valid comment syntaxs, and validate our own parsing tree.

With auto-detecting whether percentage units were vertical or horizontal the "smart" behavior turned out to be both finicky and limiting. Requiring the user to specify the axis both reduced unexpected behavior quirks and enabled more complex  layouts. Likewise I think sniffing every text file and input string and trying to figure out if it's Lua, TeX, or XML will turn into a fiasco. At the very least we'll have to stop pretending the first few bytes actually tell us anything and actually try to feed the whole blob to each parser until one of them doesn't croak.

**Comment by alerque** [comment] 2017-12-26 09:36
This issue is a duplicate of #465.

**Comment by alerque** [comment] 2017-12-29 12:09
@kappa2222 As of just now the bulk of your issue should be fixed in the master branch. You can recompile sile from that and it should work as it does before I broke it.

The catch is that "working" in this case still isn't quite what you expect. Sile can include a TeX-flavor file and splice it into the parsed tree where your include statement was, but it expects the included file to have a top level `\start{document}` tag. Your example here only has a fragment. You need to wrap that in a document tag for it to work.

I am leaving this issue open to address that because it does seem like including a fragment like that _should_ be possible, but actual regression bug was #465 and that is fixed. Now this is a feature request for a new behavior that would be more intuitive.

**Comment by kappa2222** [comment] 2017-12-29 12:51
I confirm that the problem is solved now, many thanks.

I don't mind adding a `\start{document` tag at the beginning of the included file at all.

**Comment by alerque** [comment] 2017-12-29 13:06
@kappa2222 Do be aware when you include something any whitespace (including newlines) after the opening document tag and before the ending tag is going to get brought into your host document. It might happen that where you put the include this isn't a problem, but it might introduce unexpected spaces if you pull in inline content. What might have been discarded when rendering the include as a stand alone document might not get discarded at the include position.

This seems like unexpected behavior to me and I've mentioned it in our outstanding whitespace issue #105. Not requiring the wrapping document tag would make including fragments more intuitive in my mind.

**Closed** 2019-05-28 15:16 UTC
Labels: enhancement
